### ISSUE TITLE
createpod chain element should be able support go-template based pod templates

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk-k8s#352]
## Description

We defently interested in support this kind of deployments:

```yaml
---
apiVersion: apps/v1
kind: Pod
metadata:
  name:  {{ (index .Connection.Path.PathSegments 0).Name }}
  labels: {{ .Connection.Labels }}
```

This adds flexibility to autoscale nse and it could be used in more interesting scenarios such like NSM+Application Service Mesh

## Solution

1. Make this https://github.com/networkservicemesh/sdk-k8s/blob/main/pkg/networkservice/common/createpod/server.go#L44 to string

2. Process the template with Connection values here https://github.com/networkservicemesh/sdk-k8s/blob/main/pkg/networkservice/common/createpod/server.go#L134

3. Make sure that current autoscale scenario is fine
